version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: root_db
    volumes:
      - mysql_data:/var/lib/mysql  

  phpmyadmin: 
    image: phpmyadmin
    depends_on: 
      - db
    restart: always
    ports:
      - 6060:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data: 
